theme = "monokai_pro_octagon"

[editor]
scrolloff = 0
gutters = []
color-modes = true

[editor.statusline]
left = ["mode", "selections", "spinner", "file-name"]
center = []
right = ["diagnostics", "position", "position-percentage", "file-encoding", "file-type"]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"
